# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid
import time
import memcache
from django.conf import settings
from ..models import SystemCluster


def create_init_system_clusters(apps, schema_editor):
    i=1
    cls_1 = SystemCluster(name='init_cluster_1', address_ip='123',
                          address_port='456')
    i+=1
    time.sleep(i)
    cls_2 = SystemCluster(name='init_cluster_2', address_ip='345',
                          address_port='678')
    i+=1
    time.sleep(i)
    cls_3 = SystemCluster(name='init_cluster_3', address_ip='145',
                          address_port='267')
    init_system_clusters = [cls_1, cls_2, cls_3]
    for init_system_cluster in init_system_clusters:
        init_system_cluster.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True,
                                          verbose_name='name')),
                ('address_ip',
                 models.CharField(max_length=255, verbose_name='ip')),
                ('address_port',
                 models.CharField(max_length=255, verbose_name='port')),
                ('last_update',
                 models.DateTimeField(default=django.utils.timezone.now,
                                      verbose_name='last_update')),
            ],
            options={
                'db_table': 'system_cluster',
            },
        ),
        migrations.RunPython(create_init_system_clusters),

    ]
